### ISSUE TITLE
Let's Discuss "Storm Clouds on the Horizon"  

### ISSUE THREAD

**Issue by RJP43** [RJP43/LiliElbe_EngagedLearners#1]
Each student should write in the discussion thread below 2 discussion questions after reading: 

> Pamela L. Caughie, Emily Datskou & Rebecca Parker (2018) “Storm clouds on the horizon: feminist ontologies and the problem of gender,” _Feminist Modernist Studies_, 1:3, 230-242, [DOI: 10.1080/24692921.2018.1505819](https://doi.org/10.1080/24692921.2018.1505819)    
  
In place of writing a second discussion question, students are permitted to respond in 3-4 sentences to another student's question. If you opt out of writing a second discussion question, you must mention the person whose question you are responding to (using the `@` symbol followed by their GitHub handle - e.g. @RJP43) and reiterate their question in your response.  We ask you to respect each others' pronouns when responding to one another (see our [list of Engaged Learner handles and pronouns](https://github.com/RJP43/LiliElbe_EngagedLearners/wiki/Spring-2019---Dr.-Caughie's-Engaged-Learners)). 
    
Because we are hosting this discussion on GitHub you should take note that your responses can be "marked up" using [GitHub's markdown syntax](https://guides.github.com/features/mastering-markdown/#syntax). In addition to text styling (like bold, italics, and offsetting quoted text) made available via markdown, you are also able to attach files (images are particularly welcome) and insert emojis in your responses. Please use the [GitHub Help Tutorial on basic writing and formatting syntax](https://help.github.com/articles/basic-writing-and-formatting-syntax/) along with the [emoji cheat sheet](https://www.webfx.com/tools/emoji-cheat-sheet/) to assist in writing an _**engaged**_ response.

**Comment by RJP43** [comment]
Please post by **1 pm on Thursday 2/21**.

@profPLC @zothman @tatjanawj @JackieAlfarah @Dadelinee @katebarrettmurphy @bcristiana @ElleBromer @alicapati @joaquindavalosponce @Katiegriggs24 @schola0208 @skarrow @kklimek1 @ekupchella @amandallopez @amccann2 @BMiller10 @elenipamboukis @dpedz @wravindran @Samantha9899 @nroyce @kschoen3 @jsteele1 @tinatiehen @anais-turiello @Bossa12 @kejcat

**Comment by JackieAlfarah** [comment]
**Question 1**
One question I have for this reading is knowing that technology is the the future and has become more advanced over the years, do you think the focus of Feminist scholars should remain on digital archives or should it still remain on the preservation of works of the authors? Will books still be in existence, lets say, 15 years from now? 

**Question 2**

I think the main question asked, "Can ontologies ever capture the complex, multi-layered, dynamic nature of gender identities?" is a great question, so my question will branch off this. With gender becoming more complex and changing over the years, it has taken a long time for gender or the transition of gender to be understood, so do you guys think with the study of ontology, or the knowledge of coming into existence, will ever be spot on if it is not ones self going through the changes or discovery of their true being?

**Comment by alicapati** [comment]
**Question One**
I know that the article focuses heavily on the correct usage of pronouns when encoding transgender literature and how one can decide on what/how to use a specific pronoun. Based on previous conversations and research, I know that some members of the LGBTQIA+ community prefer to use gender-neutral pronouns such as: zhe/zher, hir, sie/ze, etc. For those who work heavily on encoding this form of literature, would they ever consider using these pronouns? (Here's an article for those who may be unfamiliar: http://termcoord.eu/2014/03/gender-neutral-language/)

**Response to @JackieAlfarah Question One**
Hi Jackie :relaxed: For your first question, you address how Feminist scholars work on preserving the works of authors while also creating digital archives for influential works. Although e-text is becoming more popular, I think it is still important to maintain the physical book itself. There may be a time in which people no longer have to have a physical copy, but the novels themselves are also a piece of history. If there comes a time in which all books are available online, I think that influential works like _Man Into Woman_ could be kept in museums. Although we may not need an actual book in order to read the text, books still represent past literary movements and are key pieces of history.

**Comment by Katiegriggs24** [comment]
**Question 1**
Hi @JackieAlfarah , one of my questions is very similar to yours in asking will the study of ontology, or the knowledge of coming into existence, will ever be spot on if it is not ones self going through the changes or discovery of their true being? I want to question whether gender is something that can truly ever be defined since it something that has a different meaning depending on time and space? And how might this change the future for TEI coding?

**Question 2**
Because the notion of gender is again constantly changing, how can we go back to narratives that focus on gender identity and label characters, especially characters who wouldn't label themselves with the labels we have today? Do we just say that a character might fit into a category? And as a follow up question, do we label characters the way they see themselves or how society would perceive them?

**Comment by skarrow** [comment]
Question 1:
How does the limits in coding ontomology and the failure for TEI headers to recognize more than two genders before Hannah Kloster worked to fix the problem mirror the struggles society faced with gender? Think of Lili and the struggle her doctors had of what to call her or diagnos her as. What do we as a society have to do when we don't have the words or the words we do have are too limiting for who/what we are trying to describe?

Question 2:
In response to your first question @JackieAlfarah i would argue that books will still exist, but in digital form. What is so important about books though is it gives us a basis in which we can build our online archives and libraries. Without books the internet would lack art. It is crucial to preserve the works of authors because not only are these crucial points in history that led us to what we are experiencing today, but through the archive we can see how far we come. As the encoders struggle with correct pronoun usage, ontomology, labels, names, etc. we come to see a reflection in society and feminism of what we as a society need to work on and deal with.

**Comment by elenipamboukis** [comment]
Question 1: The article states, "It gives us access to information likely to be missed by rigid, stable, and limited ontologies. Rather than simply identifying specific types of genders or sexualities, expanding gender types by adding new terms such as “genderqueer” and “transgender." This, in short, means that there will be more information given by not specifically stating the terms of one's sexuality such as describing a character's trait. Is it possible that by doing this the reader will be left short of answers, or frustrated that the defined word isn't there? In my personal opinion, I feel as though defining and categorizing someone by their sexuality isn't fair. I feel that by saying, for example, that Lili is a transexual woman, that it completely erases the other part of who she is- her new feelings, adventures, and story. Therefore, I think that by only giving characteristics and not a defined sexuality/gender it allows the reader to gather more in-depth personal information.

Question 2: A quote from _Storm Clouds on the Horizon_ states, "Gender attributes change across times and cultures as well. Concepts of gender and sexual identity in particular change over time with the currency of new terms." Will this be an issue for the Digital Archive? There are so many attributes that could go along for people and their names, but what if it changes centuries from now? What kind of problem would that pose? I don't believe that this archive in particular would change because the attributes and elements have been defined so thoroughly, but could there be such thing as a term change? For example, within _Man Into Woman_ the term "Transvestite," was used to describe someone who got erotic pleasure from cross dressing, but now the term is known as somewhat derogatory and can stand for someone who cross dresses.

**Comment by Dadelinee** [comment]
<b>Question 1</b>
I had a similar question as @skarrow about whether it would be possible to even create TEI code that could correctly identify something that we don't even fully understand how to correctly identify in the English language. Is it possible to think of a simple TEI code that could ultimately gather all the difficult concepts of gender and how to explain it?

<b>In response to @elenipamboukis </b>
I agree that in coding we should not assume the gender a person may identify with just for ease of access. I believe that by making the coded information so ambiguous to the reader, we are actually helping to emphasize the difficulties of defining gender or transgender in simple terms because the definitions as a collective hold too much variance and information to try to even begin defining them in short words.

**Comment by jsteele1** [comment]
Question one:

Is it possible to code something gender-related, trying to be mindful of everyone's preferences of gender if it is a concept that has its own unique preference/opinion to each individual?

Answer 1:

In response to @elenipamboukis's question number 2:

I feel like this relates my question of whether or not it is even possible to code such a tricky topic of gender. I don't think this will be an issue for our archive because we know the character's preference and views. But as time goes on and new things develop I do believe it is a very good possibility for a digital archive to need to be updated because of the change in time and language progression. The problems this would pose would just be that they need to be updated with the time, so just as we have a team working to create this digital archive, there will need to be a team centuries from now to update the language.

**Comment by kklimek1** [comment]
@RJP43 Sorry but I'm having issues with the assignment. I was able to open the link in class on Tuesday, but now when I open it, I can only read the abstract, and it asks me to pay to read the full article. Am I doing something wrong?

**Comment by joaquindavalosponce** [comment]
Question 1: There is a feminist movement from Argentina seeking to change how nouns are written in Spanish and create "inclusive language"  (words in Spanish that end in the letter "A" are considered feminine, and words that end in "O" masculine). For example the word "Todos" means "all", but it ends in "os" which makes it a masculine word. For these types of words, they are proposing that they neither end in "a" or in "o", they want them to end with an "e" to make it inclusive and eliminate gender from words. Do you believe that a change like this would eliminate gender ontologies in the Spanish language and facilitate coding when translating?

Response to @jsteele1 
I think it depends on the person, on the language you are translating to, and many more aspects. In my personal opinion I would probably use nouns with the gender he/she transitioned to.

**Comment by ElleBromer** [comment]
Question 1:  The article does focus a lot on the use of correct gender pronouns especially when it relates to Lili's.  My question is how, in the future, a similar project would deal with Genderfluidity?  For example, changing between male, female, and non binary depending on the day.  This presents a unique challenge as to when to refer to the person by which pronoun, as while with Lili's you just have to look at the name being used in the narrative the theoretical person could identify with any given pronoun at any given point without a change in name.

In response to @elenipamboukis Question 2:  In this time of what some are calling a revolution of how we view gender I believe there are major changes that are going to happen very rapidly.  Gender is and always has been a social concept and how we view it may completely change, not to mention the difficulties that are faced when taking unique genders from other cultures into account while archiving.  So no, I do not think there will ever be a solid way to plan out the future of gender in the archival setting.

**Comment by RJP43** [comment]
@kklimek1 you can access the reading on Sakai under Resources > Required Essays _**OR**_ you can [search for the article on the library website](https://loyola-primo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=TN_tayfranc10.1080/24692921.2018.1505819&context=PC&vid=01LUC&search_scope=Library_Collections&tab=default_tab&lang=en_US) and sign in to your library account to access and read it.     
  
(⏬ See reference image below. ⏬ )    
  
![logintorequest](https://user-images.githubusercontent.com/8645521/53183156-6b32e000-35c0-11e9-96e8-518c7ec93b28.png)

**Comment by schola0208** [comment]
"both within philosophy and computing/information studies, there is a lot of slippage towards positivism or essentialism in the ways that ontologies are approached and understood." And while their conception of gender derives from Butler’s performativity, their methodology for producing a gender ontology may risk inadvertently reinforcing a substantive notion of gender as essentialist,"and essential. 

My question is, if the conception is right, what kind of things in a methodology may be counter-productive? examples?

**Comment by kklimek1** [comment]
@RJP43  Thank you so much! 😊

Question 1: Because so many of the characters would not identify with the labels that we would place on them today, how can we accurately create a balance between their identifications and more contemporary labels? Is there a way to code that will be flexible enough, that when our current ideas of gender become outdated, they can still be relevant in the future? 

@joaquindavalosponce I unfortunately don't have an answer, but I have a very similar question to yours. In Polish, there is a "gender neutral" way to refer to (certain) objects, but there is no gender neutral way to refer to people. (I suppose you could use the plural versions of "they", but "they" is still gendered based on whether there is a male in the group or not.) Like Spanish, pronouns and adjectives are heavily gendered, making it difficult to refer to someone in a non-binary way. When translating and coding, if Polish did introduce a neutral way to refer to people, would that make coding gender easier, especially for people who don't identify strictly in the binary?

**Comment by kschoen3** [comment]
One question I have after reading this article has to do with the progression of our ideas of gender over time. I can't help but wonder if in 100 years, our concepts of gender will have continued to evolve and complicate the language we use in order to define and categorize texts. Even five years from now, I am sure there will be progress and change in our concepts of gender, further complicating the language we use in coding. 

In response to @ElleBromer I think your point about Genderfluidity is really interesting and poignant. Once again, we run into the fact that it is probably impossible to completely and accurately define gender in code. In addition to this, the whole idea of _defining_ gender is something that many times seems to contradict the idea that gender is socially constructed and our ideas of it are ever evolving although it remains important to have a vocabulary when it comes to gender in order to discuss literature.

**Comment by schola0208** [comment]
> **Question 1**
> One question I have for this reading is knowing that technology is the the future and has become more advanced over the years, do you think the focus of Feminist scholars should remain on digital archives or should it still remain on the preservation of works of the authors? Will books still be in existence, lets say, 15 years from now?
> 
> **Question 2**
> 
> I think the main question asked, "Can ontologies ever capture the complex, multi-layered, dynamic nature of gender identities?" is a great question, so my question will branch off this. With gender becoming more complex and changing over the years, it has taken a long time for gender or the transition of gender to be understood, so do you guys think with the study of ontology, or the knowledge of coming into existence, will ever be spot on if it is not ones self going through the changes or discovery of their true being?

In response to question 2, I think the goal of these ontological studies is to track the different transitions the idea of gender has undergone up to this point. And I think that documenting as broad a range as possible is the challenge, because if we can find a way to do that, then updating that range should be a smaller problem, and we would achieve the 'spot on' you are referring to.

**Comment by bcristiana** [comment]
Can the quantum computing provide an asnwer to the challenges posed by the attempts to digitally archive the transgender and queer narratives without losing their inherently equivocal processual quality? 

@schola0208 : The difficulties mounted by the language in its attempts to catch up with the changing reality cannot be properly surprised by a markup language whose organizing principle further amplifies this tension, through restrictive categorizations. Is it worth to sacrifice semantic ambiguity for the explicitness of a programming syntax? With the loss of the diachronic fluidity, there comes the peril of essentialism, and, in creating a digital archive for the narrative of Lili Elbe’s evolving sense of self, its authors warn against these dangers and plead for an end product that remains open to both readerly interpretation and structural evolution.

**Comment by dpedz** [comment]
*Question 1* 
Due to the nature of gender changing over the years, can TEI truly keep up with these changes as gender is based on societal norms and the language's history?  


"Can ontologies ever capture the complex, multi-layered, dynamic nature of gender identities?" is a great question, so my question will branch off this. With gender becoming more complex and changing over the years, it has taken a long time for gender or the transition of gender to be understood, so do you guys think with the study of ontology, or the knowledge of coming into existence, will ever be spot on if it is not ones self going through the changes or discovery of their true being?"

@JackieAlfarah, to answer your second question, I believe that you can only capture so much of one's ontology as one can only understand so much about one's gender identity. Getting a gist of gender identities is a good first step into understanding their complexity but we probably have a long way to go. And going off of @schola0208's point, figuring out the broad range first should help with the current issues that coders may be dealing with at the moment, but language barriers restrict what we could potentially uncover with gender and properly presenting that to the public.

**Comment by amandallopez** [comment]
**Question 1**
The reading suggests that, despite discussions of transsexuality or undergoing a sex change, some texts are not explicitly about the physical "sexed" body at all, but rather about the "cultural vicissitudes of gender." _The Oxford English Dictionary_ defines identity ontologically as “the quality or condition of being the same in substance, composition, nature, properties, or in particular qualities under consideration; absolute or essential sameness; oneness.” However, humanity is moving further towards individuality. While identities continue to overlap and share similarities, do you think we will eventually hit a point where we are all so individualistic towards our identities that terms will not be able to define the subjectivity of the spectrum? Will we progress to a point of having specific categorical terms for every identity or will we reach a point where it will become obsolete? 

**Response to @joaquindavalosponce **
In regard to your question, I believe that the transition to universal terms within other languages, Spanish in particular, will be gradual, but effective, in terms of coding. I believe that taking underlying gender assumptions/signals out of words/language will be a smoother process than trying to assign each identity a letter. Considering that the identity spectrum is so broad, it would make sense to simply take gender out of language altogether. However, one also might argue that identities are so valuable to one's existence that it would be beneficial to create terms across languages that capture the broadness of ontology. I suppose it's subjective to how one views all-inclusivity. One thing that is certain is that languages across the globe must eventually adjust their terminology to present itself as universal.

**Comment by nroyce** [comment]
Question 1: I feel the same way @elenipamboukis! We shouldn't be frustrated by non-conforming genders not falling into specific categories for our personal comprehension. I believe context clues about who the person is rather than what sex they identify with should be most important. I do wonder, how will this read in future written books that include the gender fluidity that is now very present?

Question 2: Response to @dpedz : I think once we develop an adequate language that describes the person rather than the sex or gender, it will become easy for TEI to make appropriate adjustments but simply adding additional or replacing current schemas.

**Comment by anais-turiello** [comment]
Question 1: Considering the ways in which perceptions and references towards the Transgender and Queer community have changed greatly throughout time, it like likely that terms and viewpoints will evolve greatly over time, therefore changing the definition of what we now know as "modern." Will it be difficult to constantly adapt to these changes or will it be an easier process now considering that the Trans community has become more normalized in recent years?

In response to @dpedz 
I do believe that TEI can keep up with the changes in gender over time because of the many ways in which it has already adapted. If Lili were still alive today, she would probably be amazed by all the changes in society that have occurred in regards to the concept of gender and gender fluidity. Therefore, I believe us as humans are very capable of adapting to the times, as progress is a slow process and is not something that can happen all at once.

**Comment by amccann2** [comment]
Question 1: As gender and technology both develop at higher levels, we will see a strong shift in cultural and technological norms. In terms of these tech advances our devices and digital world are constantly gathering data. Considering this, do you think that it is possible to create programs that will be able to able to sense or recognize misgendering etc? 

Question 2: 
As we move forward in using the internet for preservation and also for self expression. How will we value the unprecedented amount of "feminist" or female work presented by young women online. I'm thinking about the influences of individuals like Tavi Gevinson and her Rookie Mag. Eventually will it become our duty to create preservation and archives of work like this as well to maintain that it doesn't get swept up in the internet pollution?

**Comment by Tatjanawj** [comment]
> **Question 1**
> One question I have for this reading is knowing that technology is the the future and has become more advanced over the years, do you think the focus of Feminist scholars should remain on digital archives or should it still remain on the preservation of works of the authors? Will books still be in existence, lets say, 15 years from now?
> 
> **Question 2**
> 
> I think the main question asked, "Can ontologies ever capture the complex, multi-layered, dynamic nature of gender identities?" is a great question, so my question will branch off this. With gender becoming more complex and changing over the years, it has taken a long time for gender or the transition of gender to be understood, so do you guys think with the study of ontology, or the knowledge of coming into existence, will ever be spot on if it is not ones self going through the changes or discovery of their true being?

Adding on to your first question I definitely think that the study of ontology can remain in both technology and also the author’s works. As the future changes, technology also changes and advances. This is the advantage of using technology, because it stays up-to-date and changes with the times. Therefore, as gender identities and gender studies change technology will change to adapt to it. In fact, I think that is the exact person purpose of technology, that it can be used in complex situations like these.

**Comment by Tatjanawj** [comment]
A question that I would like to pose, is after reading the Lili Elbe narrative, and having had an introduction into the encoding methods that were used for this narrative, how effective do you think the encoding methods are for defining terms in the work?

**Comment by bossa12** [comment]
My question is that since everyone is so different and as humanity develops, there will more and more term that a person wants to be referred by. Would that be too hard to keep on track? And as for the data visualization part, if there are too many categorical variables would it be meaningless to show the distribution?

@schola0208 
Hi Schola, my opinion on your question 2 is that the actual books will not disappear. A book not only carries the message and thoughts an author wants to deliver but itself is an artwork with provenance.  The electrical archive might be easy to store and publish than the actual books, but the actual book can bring a deeper relationship.

**Comment by Samantha9899** [comment]
My first question I have is about the article in a general sense, who was the intended audience for this article? Not everyone who reads this would understand the language that is being used so who is it supposed to be for since there isn't much broken down so anyone could understand. 

My second question related to @ElleBromer's question about genderfluidity, how and when would they be able to make technological advances towards this? I think it would be a hard task to figure out with encoding but it may be needed for many projects or stories.

**Comment by ekupchella** [comment]
> Response to @joaquindavalosponce 

I think that it would definitely help to add the "e" at the end. I think it's more inclusive of human and less indicative of gender. Because gender is so fluid, and people identify as more than man or woman, I think it's easier to go to one overarching term that's inclusive. It's really cool to see there be this really broad inclusive way of talking about it, and i think that's super important to see.

**Comment by ekupchella** [comment]
> **Question 2**
> 
> I think the main question asked, "Can ontologies ever capture the complex, multi-layered, dynamic nature of gender identities?" is a great question, so my question will branch off this. With gender becoming more complex and changing over the years, it has taken a long time for gender or the transition of gender to be understood, so do you guys think with the study of ontology, or the knowledge of coming into existence, will ever be spot on if it is not ones self going through the changes or discovery of their true being?

> Response to @tatjanawj 

I think representation is huge in this space, and I'm super glad that you brought it up. I'm not sure if we'll ever really "get it right", but I do think that the first step to getting there is having people, in this case trans* people, intentionally stationed in leadership roles in these works. There's so much that we discussed about the book when we were reading Man Into Woman, for example, that I had never experienced or even thought of before I read it. There are many experiences and perspectives than one person's, so when we're trying to give voice to narratives, I think it's really important that, like we're doing with this project, we're not necessarily in the spotlight ourselves, but rather highlighting narratives as they want to be told –– by those who experienced them firsthand. I think we only begin to understand the "complex, multi-layered, dynamic nature of gender identity" when it's led, at least in some capacity, by people who have experienced that shift themselves.

**Comment by RJP43** [comment]
No more submissions will be accepted for this discussion thread. Please email Dr. Caughie and me if there are any questions/concerns. Thanks everybody for a wonderful discussion! 🎉
