### ISSUE TITLE
Let's Discuss "Glands, Eugenics, and Rejuvenation in Man into Woman"

### ISSUE THREAD

**Issue by RJP43** [RJP43/LiliElbe_EngagedLearners#24]
Each student should respond in this discussion thread after reading:
  
> Kadji Amin’s "Glands, Eugenics, and Rejuvenation in Man into Woman," _TSQ: Transgender Studies Quarterly_, vol. 5, no. 4  (November 2018)  
  
_The reading can be found on Sakai under Resources in the Required Essays folder._   
    
**Please respond to either option # 1 or option # 2 by Monday, March 11, 5 PM.** Be prepared to discuss your responses and the essay in class on Tuesday, March 12th. 
  
In your response please indicate the option you are responding to, and as always because we are hosting this discussion on GitHub we encourage you to use [GitHub's markdown syntax](https://guides.github.com/features/mastering-markdown/#syntax). In addition to text styling (like bold, italics, and offsetting quoted text) made available via markdown, you are also able to attach files (images are particularly welcome) and insert emojis in your responses. Please use the [GitHub Help Tutorial on basic writing and formatting syntax](https://help.github.com/articles/basic-writing-and-formatting-syntax/) along with the [emoji cheat sheet](https://www.webfx.com/tools/emoji-cheat-sheet/) to assist in writing an _engaged_ response.  

# Option 1    
Answer both questions in a few sentences each.    
1. What is the advantage, for scholarship on transgender, of not reading _Man Into Woman_ as one of the “foundational moments in transgender history” (590)? Why is Lili the “wrong figure to be honored as a foremother of today’s transgender movement” (590)?
  
2. What is one historical fact you learned from this article that you found surprising or disturbing? 

# Option 2   
Amin draws on several concepts from other scholars to critique readings of _Man Into Woman_ as an early transgender narrative. How are these concepts defined and why are they problematic?

- Presentist history (p. 590) [not history of the present—look it up]
- Emotional rescue (Heather Love’s term) (p. 590)
- Endochronology (Jordy Rosenberg’s term) (p. 594) [not “endocrinology,” the science]
- Genealogy (Michel Foucault’s concept) (pp. 593-594, 602) [not the commonsense understanding of this term]

**Comment by JackieAlfarah** [comment]
1. 
-The advantage of not reading Man Into Woman as one of the “foundational moments in transgender history” is realizing “Lilly's story is not one of community, solidarity or social transformation. It is of the romance of an individual with modern medical science” (590). Some plot elements That were misconstrued so Lily can become a Transsexual ancestor for the present are the fact that in the book  Lily receives surgery more so to kill off her male personality, Andreas, rather than to affirm the woman she always knew she was. In the film, Lilli receives two surgeries, the first to remove the male organs entirely and the second to construct a vagina. In Man into Woman, her surgeries include receiving ovaries in the body and later a uterus. Not only are the surgeries the physical change of Lily's body and sex, but they are also about rejuvenation. By taking in the ovaries of a young woman, Lily also becomes young.Glandular rejuvenation Is the interest in the early 20th century of the glands, particularly the testicles and ovaries, as of where they came from. this was not only a sex gender and sexuality but also of Vitality and Youth. “Rejuvenation was thought to be a “wrong turn” in the history of Science and a false start in the history of transsexuality” (592). 
-The reason Lili lacks the characteristics of being a heroine in the trans community is due to her lack of involvement in the sex and gender nonconformity movements and her disgust at introverts and transvestites during as office visit to Dr. Hardenfelds clinic. She was a privileged white woman with access to  top-of-the line doctors and surgeries. 


2
-One historical fact that I found interesting was that Lili's surgeon, Warnekros, joined the Nazi party and carried out unauthorized eugenic sterilizations then later, became a Nazi eugenist gynecologist.  I think this was super creepy and disturbing. It makes you wonder if this is where Lili`s ovaries and uterus came from.

**Comment by dpedz** [comment]
> What is the advantage, for scholarship on transgender, of not reading Man Into Woman as one of the “foundational moments in transgender history” (590)? Why is Lili the “wrong figure to be honored as a foremother of today’s transgender movement” (590)?

>What is one historical fact you learned from this article that you found surprising or disturbing?

1. According to the article, Lili is considered to be the wrong figure to be honored for today's transgender movement because she falls under the catergory of a mainstream heroine. Considering that she was a white woman, she has the privilage to access famous doctors and the luxuary to afford the surgeries. Also that her story appeals to a cisgender audience as she lacks a significant involvement within the community. The advantage of not reading Man into Woman as a foundational movement in transgender history is that people can acknowedge figures that truly left a significant impact for the group and its progression to acceptance. As we know, Lili never considered herself to be a transgender person and the surgeries she unwent were more focused on her rejuvanation and to kill off her male counter part. 

2. A historical fact I found interesting was that Benjamin was able to come up with a legitimate treatment for transsexualism and coined the term gerontotheraphy. It gives us a better understanding of how far transition surgeries have came from since the 20's. Also that this doctor has shown dedication to the movement by finding a treatment for transsexualism depsite being retired.

**Comment by Samantha9899** [comment]
> 1. What is the advantage, for scholarship on transgender, of not reading _Man Into Woman_ as one of the “foundational moments in transgender history” (590)? Why is Lili the “wrong figure to be honored as a foremother of today’s transgender movement” (590)?

> 2. What is one historical fact you learned from this article that you found surprising or disturbing?


1. The advantage of not reading Man into Woman is, as the article says, it is not one if community, solidarity, or social transformation, it is the romance between an individual and modern medical science. In other stories or versions it makes it out to be a more hopeful image trying to give the readers what they want but in the actual story it tells more of a truthful side of how Lili feels. Lili does not believe that she is transgender, she believes that she was two separate people and the surgery helped her be born not transition. Lili is the wrong figure to be honored because she doesn't fit the picture of the heroine they want. Lili wasn't in any communities of sex and gender variants. She also wouldn't be a good fit with the disgust she expressed while at the clinic towards transvestites.
2. One historical fact that I learned that was disturbing is that in many case studies of transgender people they chose to ignore them and instead say they were homosexual, delusional, or psychotic. Its disturbing that people were going to doctors and instead of being helped or getting answers they were just seen as crazy.

**Comment by kklimek1** [comment]
What is the advantage, for scholarship on transgender, of not reading Man Into Woman as one of the “foundational moments in transgender history” (590)? Why is Lili the “wrong figure to be honored as a foremother of today’s transgender movement” (590)?

What is one historical fact you learned from this article that you found surprising or disturbing?

1) Lili did not see herself as part of the contemporary gender and sexual movements. She was disgusted by the "inverts and transvestites" she saw in Dr. Hershfield's office, and she saw herself as two separate beings in one body. As a sickly, infertile "_creature_", Andreas, and as a lively, healthy woman, Lili.  The surgeries she underwent to have ovaries implanted, as well as how she saw herself, align with the eugenics movement of the time. She did not bridge the gap between men and women, but rather chose the more viable option, a woman, who deserved to live because she was healthy, and because, unlike Andreas, she had the potential to create offspring.  The knowledge of medicine at the time believed that your age depended on the age of your gonads, and thus, Lili wasn't exactly transgender, but rather was just attempting to regress into a younger person. As the article points out, the belief was that the right to life belonged to the _younger_ _healthier_ individual who could thrive and reproduce, and anyone else should be sterilized (as Andreas was) or simply killed (as he was as well).

2)  At the time that Lili lived, the belief was that your gonads controlled your age, and by surgically replacing them, people could return back to their younger selves. Maybe its because I have a contemporary understanding as to why we age, and how deeply cellular that is, I find it  hard to believe that people did actually believe this, and that surgeries were actively taking place to try to prove this theory.

**Comment by elenipamboukis** [comment]
> # Option 1
> Answer both questions in a few sentences each.
> 
> 1. What is the advantage, for scholarship on transgender, of not reading _Man Into Woman_ as one of the “foundational moments in transgender history” (590)? Why is Lili the “wrong figure to be honored as a foremother of today’s transgender movement” (590)?
> 2. What is one historical fact you learned from this article that you found surprising or disturbing?

Responses-
1.) The advantage, for scholarship on transgender, of not reading _Man Into Woman_ as one of the "foundational moments in transgender history" is in Amin's words, "It is the romance of an individual with modern medical science," otherwise known in Amin's words as, "A mainstream heroine." The article says that _The Danish Girl_ movie portrays Lili Elbe as being a privileged white woman, and when looking at 'communities of sex and gender variants' she was disgusted. This is one of the reasons why the author of this article argues that Lili is the wrong figure to be honored as a foremother of today's transgender movement. When I read this I acknowledged the other point of view on _Man Into Woman_, but honestly I have to disagree. I don't think that anyone has 'privilege' when going through a sex reassignment surgery, I think that it would be very difficult for anyone to deal with any situation regarding who they are, their sexuality, or where they belong in the world. It is a very difficult situation to be in, and to say that about Lili I was just completely appalled. 
2.) One amazing fact about transexual history- "The availability
of synthetic testosterone and estrogen would later render ovarian and testicular
grafting obsolete as sex transition surgeries, just as the ascendance of the “trapped
in the wrong body” trope would take precedence over alternate explanations for
gender variance, including the action of internal ovaries or testes or the sense
of having multiple differently gendered personalities." I, personally, didn't know about multiple different gendered personalities and looked into it a bit more and found that there are more than 13. I actually found that there is a HUGE debate about whether or not there are more than two genders, although I have to say that I think people should identify with whatever they feel is right!

**Comment by schola0208** [comment]
#question 1  
* The advantage of reading the text not as > One of the foundational moments in transgender history is that it allows for nuance, and challenges one to keep in focus what the transgender movement stands for. Reading the text as indeed one of the foundational moments in transgender history,  that history would have to be linear, and the text would have to share at least the key ideas and realities of the transgender movement. The text does not necessarily do that and so should not be read as such for the same reasons that Lili is the > Wrong figure to be honored as a foremother of today’s transgender movement . Besides the fact that the terminology overlaps and has evolved over time, some of those reasons include the fact that Lili embodies many of the normative behaviors of social order, like excessive femininity, yet many trans people would not share that desire to comply with the hegemonic order. Additionally, Lili is not interested in community, agency, or at least concern for other trans people, and is thus unfit to be the mother of a _**movement**_ centered around those values.
* the most shocking historical fact is just how far these people were willing to take social hygiene 😞. It left me wondering where fields like neuroeconomics or gene-testing will take us, and in what ways the economic and political desperation of the 20s and the 30s echoes with the environmental and economic inequality crises in the present.

**Comment by Dadelinee** [comment]
<b>1. What is the advantage, for scholarship on transgender, of not reading Man Into Woman as one of the “foundational moments in transgender history” (590)? Why is Lili the “wrong figure to be honored as a foremother of today’s transgender movement” (590)?
2. What is one historical fact you learned from this article that you found surprising or disturbing?</b>

An advantage of not reading <i>Man into Woman</i> as a foundational moment in transgender history or for studying transgender people is that Lili herself did not identify in this way. In fact, she was before the term transgender. Her transition in the novel was more focused on killing off her male counterpart, Andreas, as well as rejuvenating herself as Lili to be younger. Transgender history is not based on such concepts and the procedures may be the same yet the purpose of them is different in the transgender community. Lili is the wrong figure to be honored because she herself would have never identified in the community that would be honoring her. Her reasons for transition don't align to the transgender communities' and are more to give her the ability to take over her body for herself and kill off Andreas. 

The historical fact I found surprising was the fact that medical practitioners fully believed that the gonads of a person could determine their age. In theory, the concept seems somewhat logical if you're correctly addressing it in the way they believed, that is with the ability to reproduce and remain fertile, however biologically, it's rather silly for them to believe that by replacing old gonads with new ones that they would realistically be able to "fix a person's age."

**Comment by kschoen3** [comment]
1. What is the advantage, for scholarship on transgender, of not reading Man Into Woman as one of the “foundational moments in transgender history” (590)? 

Not using Man into Woman as a foundational moment in transgender history allows for space to be made for more marginalized trans people. This novel, in many ways, upholds normatively in gender, Western social structure, and ideas etc. If more attention was paid to other trans people in the past, as well as other documents and narratives, trans scholarship would be less influenced and informed by normatively and therefore more aligned to today’s transgender movement.


2. Why is Lili the “wrong figure to be honored as a foremother of today’s transgender movement” (590)?What is one historical fact you learned from this article that you found surprising or disturbing?

I find the fact that eugenics, which is condemned in our society today, is so integral to the history of transgender. I think it is important to recognize that many eugenic philosophies and practices were first practiced primarily in the US. Important and wonderful historical figures like W.E.B. DuBois and Magnus Hirschfeld have paved the way for social improvement but remain highly problematic. In fact, it seems they become more complicated as time progresses. It is interesting to see how we, as a community dedicated to justice, address these figures.

**Comment by tinatiehen** [comment]
**Option 1:**
1. There are a considerable amount of advantages, for the scholarship of transgender, presented in Glands, Eugenics, and Rejuvenation in Man into Woman that disregard Man into Woman as one of the “foundational moments in transgender history”. Specifically,  author Kadji Amin expresses that the novel glorifies the oddity of a scientific sex transformation. While Lili Elbe’s story marks the first documentation of a sex change, her narrative lacks understanding toward a progressive change in social stigmas and the transgender community. Lili’s attitude throughout Man into Woman essentially dissociates her from the many transgender people struggling to find a voice in a society that rejected their interests. Lili, being privileged enough to undergo such a medical procedure, could have encouraged others like her to help create a new model for society for years to come. However, I thought it considerable to note that the modern world is very fortunate to have access to the letters and memoranda documented by Lili and her loved ones during a certainly difficult and intimate shift in her life. While the narrative can be exaggerated to appeal to the people of the time, there is no misconception that Lili was extremely brave, a heroine to herself, in her decision to transition. Many other transgender people sought courage from Lili’s journey, despite the emotional turmoil associated with defining one’s identity.

2. One historical fact I learned from this article that I found surprising was Dr. Hirschfeld’s theories on homosexuality. I am aware from class discussion that Hirschfeld, and many other experts in his field, considered homosexuality to be of organic roots and thus, “curable”; ultimately concluding the sexual character to be immoral. However, I was unaware that he also considered same sex intimacy a “disorder of evolution” or even as “preventative means”. These approaches suggest that we have homosexuality to thank for preventing a degenerate family line from continuing to reproduce. I thought this was interesting because such reasoning would contradict Hirschfeld’s original thought by saying homosexuality is actually “incurable”. I find both considerations to be quite cringeworthy; it is enough for an individual to be labeled outside of the “norm” of heterosexuality, but classifying sexuality, which we now know to be fluid relative to character, within the realm of amendable medical conditions completely ignores the conversation surrounding emotional intelligence and identity. I thought it also intriguing to consider Hirschfeld's speculation in a contemporary context; today’s technology allows for enlightening genetic tests that could elaborate on the meaning of a “degenerative” family line. Also, many gay couples find it favorable that genes may be extracted and delivered to a surrogate, allowing them to defy the so-claimed ruinous laws of evolution.

**Comment by nroyce** [comment]
>What is the advantage, for scholarship on transgender, of not reading Man Into Woman as one of the “foundational moments in transgender history” (590)? Why is Lili the “wrong figure to be honored as a foremother of today’s transgender movement” (590)?

Amin is pretty clear that he believes _Man Into Woman_ this is more of a **rejuvenation** piece rather than transsexual text. The focus is more on the endocrine and physical body parts and the division of 2 people in which 1 has to die for the other to survive, rather than a being who feels suppressed in a body and gender that were assigned to them that they don't identify with.  I still believe Lili is a figure to be honored but could be offensive in this older text and way of thinking where she shuns the homosexuals and transvestites.  That only furthers the fight for transgender normative beliefs.


>What is one historical fact you learned from this article that you found surprising or disturbing?

I found it a surprising and different way to understand the maturity of a person could be updated with "a new life and a new youth" which meant to Steinach "A man is as old as his endocrine glands." Lili further adds that she feels much younger that her age of 47 after she receives ovaries donated by a 27 yr old. 
:older_man:  Into --> :woman:

**Comment by bcristiana** [comment]
**Option 2**
Kadji Amin wants to have his cookie and to eat it. In the 2015 movie *The Danish Girl*, based on an adaptation of Lili Elbe’s life narrative, *Man into Woman*, he sees an attempt by the mainstream media to conveniently falsify the transgender history, for both commercial and definitional purposes. To prove that this is the wrong narrative, and Lili Elbe the wrong person to inaugurate the pantheon of queer inspirational figures, Amin employs a varied set of conceptual tools and a suitably selected factual base for his arguments. He contends that the `glandular rejuvenation in the guise of sex transition therapy` (601) is the real drive of Elbe’s tribulations and connects the sex-centered dawn of the last century with a system of `racialized biopolitics and eugenics` (597) for which she serves as an illustration of biologically fit, normative femininity (601).
For Amin, Lili’s death is an `emotional rescue` device and one of the narrative’s sins. Thus, her shortly lived womanhood unties cathartically the transgender identity from the pathological stigma, while it obscures the positivist belief at the time in biology as the remedy of all the ills that threaten the whites’ racial superiority. Discontented with a film that voids the past of its specificity in order to infuse it with the present day understanding of transsexuality, Amin commits himself the presentism fallacy. In judging Lili as interested rather in rejuvenation than in sex alteration, not only does he replace the effect with the cause, but expects from her a behavior that typifies the present acception of transgender, at a time when its conceptual awareness didn’t exist, much less the language to express it. The way he interprets it, the film asserts a linear determinism that links the problematic past of transsexuality with its present, within an endochronologic framework whose apparent simplicity conceals the `sexological and colonial forms of knowledge-power` (591) and whitewashes the biopolitical eugenics (594). Thus, Amin argues that Lili’s fictional memoir doesn’t belong to the queer `wrong body narrative`, but takes `the glandular conception of selfhood to its logical limits` (596). While Lili’s surgeries closely precede the Nazis’ rise power, and her surgeons’ careers become entangled for the better or for the worse with the state-enforced eugenic project, Amin substitutes again the subsequent for the antecedent and connects speculatively the source of her ovarian transplant with the forced sterilization program (601). He takes the next step and, in a twisted syllogism, links the ovarian transplant to the rejuvenation as part of the `efforts to direct reproduction` (598), and Lili’s case of sex reassignment surgery to the attempts `to fix sexual degeneration and restor[e] . . . ‘healthy’ sex polarity` (599).
At times conflating this fictional memoir and its cinematic version, though the latter is one degree farther from the reality than the former, he criticizes a literary discourse with the tools of sociologist when, in yet another anachronistic fallacy, considers the transgenderism of both *Man into Woman* and *The Danish Girl* not intersectional enough because it does not deal with the `hierarchical structures of value and silent modes of normativity` (590). Yet he ignores the influence of Foucault’s systems of power-knowledge in the shaping and creation of the subjectivity, that is, the very mechanism at work in the repudiation of the scientific racism at the end of WWII. It is the French philosopher’s concept of genealogy as historical process subjected to contingent forces that he appeals to in analyzing the relation between `this past and contemporary transgender politics` (593), as opposed to the endochronological predictability. In this way, he can reveal inconsistencies and uncomfortable truths and demonstrate that `there is nothing presumptively innocent about the trans subject across time and place` (603). After advancing some very strong conclusions based on speculative conjectures only, in the end, he describes the genealogy that he advocates for as `open to multiple ramifications and often contradictory origins` (602). If now, as then, the biopolitics of transgenderism involves tensions engendered from the same multiple systems of oppression and privilege (602), maybe this study focuses on the wrong period and with the wrong tools.

**Comment by Katiegriggs24** [comment]
**Option 1**

1.What is the advantage for scholarship on transgender, of not reading Man into Women as one of the "foundational moments in transgender history"(590)? Why is Lili the wrong figure to be honored as a foremother of today's transgender movement"(590)

The whole point of Amin writing this article is to pull away from the traditional thought that narratives like MIW are supposed to be read as a transsexual autobiography but instead understanding them in terms of the characters being rejuvenated. If we start to look at it from this perspective, it broadens the understanding of what transitioning medically meant during those times. Lili would have been the wrong figure to be honored as a foremother of today's transgender movement for many reasons like, "she  visibility relies on the hierarchical structures of value and silent modes of normativity that render a relatively privileged white woman with access to doctors and surgery an appealing mainstream heroine."(Amin). As well as Lili's lack of  involvement with the different communities of sex and gender variants, and her blatant disgust at the inverts and transvestites she encounters. She simply didn't think of herself as being anything less than a women, showing that she wouldn't consider herself apart of today's transgender movement and ultimately the wrong figure to honor as a foremother of today's transgender movement.

2. What is one historical fact that you learned from this article that you found interesting or surprising?

Something that I found interesting scholars reread sexual inversion as a figure of gendered differences instead of reading it in terms of sexually deviant desires which kind of breaks down the stereotypes that gendered differences is something that isn't apart of the norm.

**Comment by alicapati** [comment]
**Option One**
> 1. What is the advantage, for scholarship on transgender, of not reading _Man Into Woman_ as one of the “foundational moments in transgender history” (590)? Why is Lili the “wrong figure to be honored as a foremother of today’s transgender movement” (590)?
> 2. What is one historical fact you learned from this article that you found surprising or disturbing?

**1)** As Amin discusses in his article, "Glands, Eugenics, and Rejuvenation in _Man into Woman_," Lili Elbe does not view herself as transgender, in fact, she views herself as an entity entirely separate from her male counterpart, Andreas. They are two individuals who occupy the same body. As he states, "For her part, Lili's overwhelming desire is less to be rid of a 'wrong body' than it is to stop sharing this body with Andreas, her usurper" (Amin, 596). It would not be fair to dub her as the "foremother of today's transgender movement" if she did not identify as such. To further strengthen this argument, Amin consults the text of _Man into Woman_, saying, "...her lack of significant involvement with communities of sex and gender variants, and her disgust, in Elbe's multiply authored 'memoir' _Man into Woman_, at the inverts and transvestites she encounters (in her male form as Andreas) at Dr. Hardenfeld's clinic" makes her an even less qualified candidate to be a prominent figure of the transgender movement (Amin, 590). For us to classify Lili Elbe as a founder for such a movement could almost be considered an insult to those who struggle with the idea of being transgender. Lili is not shunned by the ones that she loves, as they view Lili as a woman and Andreas as a man. She does not exhibit any major signs of dysphoria throughout _Man into Woman_. She sees herself as a separate person from Andreas and sees to it that she is able to live her life as a "complete" woman.

**2)** Although we touched on it in class, I was surprised to read about Magnus Hirschfeld's thoughts on homosexuality and how he related it to eugenics. In the article, it is written that "he simultaneously speculated that homosexuality might have evolved as a 'preventative means' against degeneration, ensuring that a degenerate family line would die out. In this eugenic line of reasoning, homosexuality ought _not_ be cured, because that would permit the reproduction of a degenerate family line" (Amin, 599). I find this difficult to understand where he was coming from, as Hirschfeld also identified as being homosexual. Wouldn't that mean that his family line would also be considered "degenerative"? 😕

**Comment by skarrow** [comment]
Part 1: I think the advantage of not reading Man into Woman as the
foundational moment in transgender history is recognizing the community
Lili is apart of. At the time the author of the book had to be careful of how
he might be censored, so he had to make Lili seem very different from the
rest of the transgender community. There’s even the scene within the book
where Lili feels she doesn’t fit in with the other cross dressers in the
doctors office. This scene sets Lili apart from the other members of the
trans community, and emphasizes the idea that Lili was not weird like the
other members. Some of the language used to make Lili seem like a true
and pure woman, intentionally or not, discredits a lot of the other trans
community members at the time. Also, as Amin suggests Lili is easily
approved by cisgender audiences because of her white, richness, and
access to advanced medicine. The quote that stood out to me most at the
beginning of the text was “Lili’s story is not one of community solidarity or
social transformation it is a story of an individual’s romance with modern
medical science,” (Amin). Which, in a nutshell, explains the problems with
the movies focus on Lili as the first to undergo transgender surgery and as
the valiant knight to set this movement in motion.
Part 2: One historical fact that I learned was that back then it was widely
accepted that one’s sex defined the person and life itself. Early
rejuvenation therapies use ovaries and testes to redefine the person and
give them a younger spirit. The essay explains how Steinach saw sex as
the key to life itself. “It is the root of life. Just as it produces physical and
psychic maturity, induces and preserves the period of flowering, shorter or
longer, here richer, there poorer, so it is also responsible for the withering of
the body and gradual loss of vitality. Sex is therefore the obvious means for
natural stimulation or “activation” in youth, and also the instrument for
methodical “reactivation” in old age. Sex is not only the measure for the
rise, peak, and fall of the currents of life, but also, up to a point, for their
restitution. (1940, 11)” This emphasis on sex explains key narration
elements in the text and the movie on the major character shifts between
Lili and Andreas and the ‘need’ for Neils Hoyer to portray Lili and Andreas
as two completely different people.

**Comment by ElleBromer** [comment]
1.  The advantage of not reading this as a foundational moment in transgender history is you are able to see it as it is, not as it can be romanticized.  This is not truly the story of a transgender woman or someone who fought for transgender rights, this is something completely different for someone who apparently actively reviled the community that she found herself near.  Thus she is also the wrong person to be honored as there are so many more deserving figures that deserve to be honored.

2.  One thing I found surprising was just how much influence eugenics had on this field of study.  I am well aware that eugenics as a concept was at its height around this time but it is not something I ever considered to be important to LGBTQ history.  I suppose looking back it seems like it should have been obvious and yet this is the first I truly thought of it.

**Comment by bossa12** [comment]
1. What is the advantage, for scholarship on transgender, of not reading Man Into Woman as one of the “foundational moments in transgender history” (590)? Why is Lili the “wrong figure to be honored as a foremother of today’s transgender movement” (590)?

- The advantage, for scholarship on transgender, of not reading Man Into Woman as one of the "foundational moments in transgender history"  is because of that Lili herself doesn't see herself in that heroic way. Lili hasn't review herself as a transgender but a struggle unity of two identities of Andreas and Lili. The surgery for her is a transition from two into one, to get rid of a "wrong body". 

2. What is one historical fact you learned from this article that you found surprising or disturbing?
- One surprising fact to me is that "male homosexuality was caused by a failure of the gonads to achieve full sexual differentiation" and male homosexuals were "prone to cyclical symptoms".

**Comment by RJP43** [comment]
This discussion thread is closed. Please email Dr. Caughie with questions and concerns if you forgot to post or submitted your response after 5 pm yesterday. See you all Thursday for team time!
