### ISSUE TITLE
Error message concerning phrase "en bog"

### ISSUE THREAD

**Issue by kejcat** [RJP43/LiliElbe_EngagedLearners#38]
When I coded the title of the Sanheden article, I got an error message that said, "Attribute name "bog" associated with an element type "En" must be followed by the '=' character." CODING: `<item rend="primary"><b><En bog om, hvordan <persName key="wegenerE">Hr. Wegener</persName> blev til <persName key="lili">Frøken Wegener.</persName></b></item>`. How can I fix this? @kejcat

**Comment by RJP43** [comment]
:eyes: What's the text of the title?
  
I am not sure why you have a `<b>` element thrown in there? And while that is not causing the specific error you mention it should throw a validation error because it is not in our guidelines or our schema. We should meet so I can verify you have the latest schema associated correctly.   
  
What is causing the error you report above is the erroneous opening angle bracket `<` after the start tag of that random `<b>` element.

**Comment by kejcat** [comment]
The headline is "En Bog om, hvordan Hr. Wegener blev til Frøken Wegener." 
I took out the random bracket and that fixed one error. Now I have one that says: element "b" not allowed anywhere; expected the element end-tag, text or element "add", "choice", "corr", "date", "del", "figure", "foreign", "gap", "hi", "label", "list", "listTranspose", "metamark", "note", "num", "orig", "p", "pb", "persName", "placeName", "reg", "seg", "space", "subst", "title" or "unclear"
The <b> element is to indicate that the text is bold. Is there another way I should be indicating that the text is bold? Or, should I not even worry about that because it already is designated as a headline?

**Comment by RJP43** [comment]
:eyes: please see the [mimicking print stylistic renderings section of the guidelines](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/encodingGuidelines.md#mimicking-print-stylistic-renderings)
