### ISSUE TITLE
better way to code TEI header

### ISSUE THREAD

**Issue by kejcat** [RJP43/LiliElbe_EngagedLearners#43]
Becca,

I wrote a note in our meeting that you recommended I look at the TEI header lesson for a different way to include a title that has a translation. I couldn't find anything in the TEI header on this subject. What am I missing? 

Thank you!

Kristin

**Comment by RJP43** [comment]
:eyes: @kejcat after looking over several other documents I decided to just have the title in the teiHeader be the English version since the two titles (original and translation) are being represented in the main  `<text>` of the file - generally in the `<head>`. Sorry about the confusion. What I have in the [teiHeader template](https://github.com/RJP43/LiliElbe_EngagedLearners/blob/master/ProjectDocs/TEIHeader_Template.xml)  will but what I am looking for when transforming to HTML. Thanks! 👍
