### ISSUE TITLE
2019 Summertime Volunteer Tasks

### ISSUE THREAD

**Issue by RJP43** [RJP43/LiliElbe_EngagedLearners#47]
Hello volunteers :wave:  

Thank you for continuing work on the _Lili Elbe Digital Archive_! 🎉 This issue is where we will organize and assign your technical tasks from May 2019 until August 2019. 

As you complete a task please feel free to check-off the associated box.  
***  
_Please note there will be more tasks added to this list as the months ensue and our website launch nears. Tasks might also change or become more developed so please check in here regularly._    

# @Dadelinee Tasklist  

- [ ] Finish encoding [Spring2019_SecondBatchGermanLetters](https://github.com/RJP43/LiliElbe_EngagedLearners/tree/master/ProjectDocs/archivalMaterials/German_archive/Spring2019_SecondBatchGermanLetters/Translation_Transcription). _You might find it useful to look over the issue where I first assigned these documents to your EL classmates here - #42_

**Comment by bcristiana** [comment]
Hi, @RJP43 , don't know if you saw my email, so I thought to signal here too my willingness to join in the work.

**Comment by bcristiana** [comment]
@RJP43 , I think I pressed the wrong button--I did it the second time and I apologize. I hope I reopened the issue.

**Comment by RJP43** [comment]
@bcristiana I am away at conferences for the next few weeks ... so a bit busy... nevertheless I am checking in with @ProfPLC and Emily to determine where we could best assign you tasks. I will get back to you ASAP.

**Comment by Dadelinee** [comment]
@RJP43 I'm not sure if you want us to address questions about the encoding here or not <:^). But, for one of the German letters (1931-12-28) there's a comment on the translation doc that states that one of the letters in a word on the original document was cut out from a hole puncher, however, Tatjana said she assumed it was a "g" in her comment and I was just curious what the correct code from the guidelines is to illustrate that. Should I use the "note" code or is there another one specific to an issue like this?

**Comment by Dadelinee** [comment]
@RJP43 I noticed while encoding the German letter 1931-12-28 that in the transcription/translation document, a word is missing that was in the facsimile image. In the image, the sentence says "Leider jedoch muss ich aus Ihrem Brief an Frau Diel ersehen" but in the transcription it says "Leider jedoch muss ich aus Ihrem Brief an Frau ersehen" and it's missing the "Diel" part (both in the transcription and translation) and I wasn't sure how you wanted me to go about fixing that? Also, for the same letter, once I finish the encoding, I think all the `<add>` elements and `<subst>` elements plus their descending elements will need double checking since it was my first time working with that code so I'm not sure if I did it right. Thanks!

**Comment by Dadelinee** [comment]
@RJP43 Oops also forgot to mention that "Harry Schumann" is missing from the prosopography, as well as Frau Diel. And for the `<add>` elements, one of the attributes says "rend" yet I'm not sure what medium to fill in for it when the letters that were inserted weren't inserted with black ink but instead it looks like they were typed over with whatever ink the typewriter used as if they went back and manually typed over it as opposed to handwriting it in. Since the only options for "rend" seem to be "pencil" or "redCrayon", basically utensils you use for handwriting instead of them physically typing over the letter with the typewriter, I wasn't sure what to put in for the value so for now I just left it blank.

**Comment by RJP43** [comment]
:eyes: @Dadelinee thanks so much. Keep up the great work and documentation. I will be addressing all of your concerns when I return from Pittsburgh after June 10th. Please contact Emily or @ProfPLC with any immediate content concerns or to be assigned additional tasks. 💟 

@bcristiana and @kklimek1 please be in contact with Emily (via email -  manintowoman@gmail.com) if you are still looking to be assigned summer work; otherwise, I will check in when I return to Chicago. 

Hope you all are enjoying your summer! 🌞 🏖

**Comment by bcristiana** [comment]
@RJP43 , thank you for the advise. I took some time to translate the 1st issue of the Voila text and just sent it to Emily--just in case. I wish you a productive and fun time attending those conferences. Take care and don't forget to give yourself some respite!

**Comment by bcristiana** [comment]
@RJP43, hi! I looked over the proofing instructions and, while I've located the XML version of Il et Elle to work on in Oxygen, I can't find the HTML version to download. Where can I find it?

**Comment by RJP43** [comment]
@bcristiana I worry when you say you have located the XML in oXygen. All files (xml, html, schema, etc.) should be downloaded fresh at the start of each work session and those files changed uploaded after each work session from/to this GItHub repo. If you want we can ask @emilydatskou to set up a phone call meeting between us to review the process pending if she and @ProfPLC think it is worth us spending time to do so.

**Comment by bcristiana** [comment]
@RJP43 , hi! I can see why you read it that way and why you'd be worried. What I meant is that I located the XML file and that I will be working on it in Oxygen. I apologize for the ambiguous way of expressing an idea. What I had trouble with was finding the HTML version of the text, but Emily has provided me with one. If I have a problem, I thought that I could ask for your help via Git/Issues or email. I know how busy you are and am mindful of your time. My intention is to help, not to create problems. If you are uncomfortable with me proofing the text, please let me know--after all, you probably know my limitations better than me.

**Comment by RJP43** [comment]
@bcristiana no no I think you will be great at correcting the text. Thanks for the update. Please reach out here or via email with any questions. 💟👍

**Comment by bcristiana** [comment]
@RJP43 , hi! Thank you for your support! I have uploaded the HTML version with the changed css line in the header. I sent you an email with the modified xml version of Il et Elle attached as document, as well as a Word document with a missing fragment of translation. If you give me the green light, I will upload the xml text on GitHub. I will start now recording on Google Sheet the changes made in xml and the possible errors that I noticed, but left unchanged. This is to make sure that you'll see the email. I hope I don't overburden you.

**Comment by bcristiana** [comment]
@RJP43 , I finished filling in the Google Spreadsheet. I will be waiting to hear from you. I really hope that I didn't mess up. Remember to give yourself a break!

**Comment by emilydatskou** [comment]
@bcristiana, thank you for letting us know and for your detailed comments. @ProfPLC and I will review your comments and get back to you! (Also, this is my first Git comment so hopefully I did it right!)

**Comment by bcristiana** [comment]
@RJP43 , @emilydatskou , hello again! I managed to upload the XML version of Il et Elle and the Word doc with the missing translation (I didn't realize that I had to sign in again). Hope everything is fine. Thank you for your patience.

**Comment by emilydatskou** [comment]
@bcristiana, @ProfPLC has reviewed about half of your comments on the Google spreadsheet and has left comments for you on what needs to get changed and what particular ids should be used. She will finish her review tomorrow. I've gone through what she has done and highlighted in bright blue and left a comment for you in the changes that should be made. Note, some of the changes require changes to the prosopography so you will have to wait until @RJP43 or Dr. Caughie make those changes. Cells highlighted in yellow are for Rebecca and Dr. Caughie so you can ignore them. I will update again when Dr. Caughie finishes her review. Let me know if you have any questions!

**Comment by bcristiana** [comment]
@emilydatskou , I will be looking over and come  here if I need more explanations. Thank you for keeping me up to date. Welcome to GitHub Issues!

**Comment by bcristiana** [comment]
@emilydatskou , @RJP43 , I uploaded 1Ilet Elle, which contains the changes to the XML text, based on the Google Spreadsheet comments. Except one entry, "Professor G", which was already tagged and, therefore, I don't know why I mentioned it, I took care of Prof. Caughie's notes. Will be waiting for the rest.

**Comment by emilydatskou** [comment]
@bcristiana, thanks for getting the changes made so fast! @ProfPLC has finished the rest of her review. I highlighted in bright blue the changes you need to make but please make sure you are paying attention to Dr. Caughie's comments in case I missed any. Please note, for those comments that are repeated (for example, when you note each time Paris is missing a tag), Dr. Caughie only made the comment once so make sure you apply the change throughout the document. @RJP43 and Dr. Caughie also updated the prosopography today so all ids noted in the spreadsheet should be added. Once you're finished making changes, let me/us know. Also let us know if you encountered any issues or if there were any changes you could not make. Thank you!

**Comment by bcristiana** [comment]
@RJP43 , @emilydatskou , this is to let you know that I uploaded 12IletElle on GitHub. It contains all the changes of the XML text, according to the comments that Prof. Caughie and @emilydatskou  made on Google Spreadsheet. There are some required changes that I am unable to make because I don't know how. They are related to styling the text (@RJP43, I am so sorry, I forgot how to (de)italicize the text!) and finding or, perhaps, creating (key)IDs. All these are mentioned in my comments in column F. I would like to read the text in HTML once more, because in this format I can more easily follow in parallel the original and the translation and see if the persons and the places are tagged identically. To this aim, I wonder if you could turn 12IletElle in HTML, so I can have the updated text on which to follow the tagging. The plan is to make any necessary adjustments in XML. ULtimately, this would become the final version of HTML, that is, a text more correct than it is now. I will also send you both this as an email, to make sure that you are updated.

**Comment by bcristiana** [comment]
@emilydatskou , I just saw your email. I will start to assemble the list of the unattained changes and transfer them from Google Spreadsheet here. I didn't think that it would be easier this way.

**Comment by bcristiana** [comment]
@RJP43 , @emilydatskou , these are the changes to be addressed:
1). In f2, (Hand Christian) "Anderson" needs a key ID.
2). In #f09, #f11, #f14, #f40, #f43, "The Wegeners", as a plural, needs a key ID.
3). In #f14, and f21, "Baroness Goldschmidt-Rothschild" needs a key ID. 
4). In #f23, Marquise de S.G. needs a different key ID than her husband, Marquis de S.G.
5). In f25 and #f25, respectively, "archeveque de Naples" and "archbishop of Naples" have the same key ID, but are differently marked in hyperlink: one as "archeveque" (f25), and the other as "archbishop of Naples".
6). In #f28, Chateau de L'Oeuf bridge does not have a key ID.
&). In f60, #f61, f 62, #f62, both of the letters and the first's postscriptum should be in italics.
7). In f65, "Son portrait" should not be in italics.
8). In #f65, the letter should be in italics.
9). In f71, "belle-soeur" (Lili's sister-in-low) doesn't have a key ID or an ID.
10). In f77, "Frauenklinik"  and "it" should not be in italics.
11). In #f77, the letter should be in italics.
12). In #f80, Patient", "wife", "notary", "nurse" do not have IDs.
Thank you for looking over them.

**Comment by RJP43** [comment]
@bcristiana I will make these corrections in the XML and schema. Now that the website is live I will be making edits to the XML directly answering comments and old GitHub issues when it comes to materials worked on in the EL class. Once I have made all the corrections on my end I will rerun the transformation pipeline to turn the file into HTML. I will let you know when it is live for you to look over it again. THANKS for your hard work.
